### PR TITLE
Ensure that the clean threshold for the final image is never higher than the clean threshold for the initial image

### PR DESCRIPTION
**Pull request by psheehan**
It turns out that due to the way that the clean threshold for the initial image is calculated (from the theoretical sensitivity with a DR-modifier) compared with the way the clean threshold for the final image is calculated (from 3*RMS_NF_curr as calculated from the post solint images), it can occasionally be the case that the clean threshold for the final image is higher than the clean threshold for the initial image. This can lead to oddities such as apparent increases in the RMS of the final image or decrease of the SNR, simply because the final image is not being cleaned as deeply as the initial image.

To fix this issue, this PR adds a condition that the final image clean threshold should be `min(selfcal_library[target][band]['clean_threshold_orig'], 3*selfcal_library[target][band]['RMS_NF_curr']` so that we fall back to matching the initial image in the event that the RMS would be a higher threshold. We also now track `'clean_threshold_orig'` so that this is possible. 

For VLA datasets, where the initial clean threshold is not set by DR modifiers but is rather cleaned to nsigma=4, we use the results of the tclean return dictionary (which is now saved) to find the peak residual at the end of the final major cycle and use this as a proxy for the initial clean threshold (as it should be <= the original clean threshold). Unfortunately the actual threshold used is not stored, but this should be close enough.

### CODE REVIEW

**Comment by psheehan** [comment]
As a note, @jjtobin, I've tested that this works for an ALMA dataset where this was an issue. I also forced it to go the VLA route of using the tclean return dictionary to get `'clean_threshold_orig'` and that appears to have worked. So I believe this should be good to go. But if you happen to know of any VLA datasets where this has been a problem... might be a good check?

**Comment by jjtobin** [comment]
Would it be somewhat cleaner to store the tclean return dictionary in the selfcal_library for each image, that way you don't need to add pickle loading code?

**Comment by psheehan** [comment]
I think I did it this way because at least as of now, `tclean_wrapper` doesn't know about selfcal_library and thus couldn't pass it directly in. But if we did want to do it this way, I could get the tclean return dictionary within `tclean_wrapper` and make it a return value for tclean_wrapper, if we want to go that way?

**Comment by jjtobin** [comment]
Ahh yes, I was thinking about this from the refactor_code point of view. This change is probably less invasive for my main then.

**Comment by psheehan** [comment]
Yeah, once we merge this in to refactor_code, I think it would make sense to store it straight into selfcal_library.

It might not be toooo invasive here, though - if we make it a return for `tclean_wrapper`, if we don't store it when we call `tclean_wrapper`, it'll just end up discarded. So it would probably be ok. Let me know if you want me to do this, otherwise we can merge here and make it happen under-the-hood when we get to refactor_code

**Comment by jjtobin** [comment]
That might be the best option to make it a return from tclean wrapper.

**Comment by psheehan** [comment]
Ok, I've updated the code to now have `tclean_wrapper` return the tclean return dictionary. Then only the call to `tclean_wrapper` for making the initial image actually catches it and uses it slightly later to store the initial "clean threshold". 

I don't store the full dictionary as we thus far haven't needed any additional information from it. And when we merge this forward to the refactor_code branch, it might make more sense to store the info that we want from it within `tclean_wrapper` rather than storing the whole dictionary.

I've also tested it and it is working properly, so this should be good to go unless you have any other thoughts?

**Comment by psheehan** [comment]
Oh wait, it's not good to go because it appears that there are now conflicts... Oops. Probably from merging a bunch of other PRs just now

**Comment by psheehan** [comment]
Ok, should be fixed now and ready to merge.

**Comment by jjtobin** [comment]
since we return the tclean dictionary with every tclean_wrapper call, will this now result in the tclean return dictionary getting printed to the stdout?

**Comment by psheehan** [comment]
It doesn't (to the best of my knowledge and from a quick check of the last run I did with this) because Python scripts only spit to the stdout if you explicitly call `print`. Function returns that aren't captured only to to stdout for IPython, I believe

**Pull request merged**
